keyword_dict = {
    # Tooling
    "fdk": ["fdk","freshworks development kit","freshworks developer kit","freshworks cli", "code coverage"],
    "uikit":["crayon","ui kit","ui components","fw-"],
    "api-sdk": ["api sdk"],
    # Features
     "smi": ["server method invocation","smi","client.request.invoke","request.invoke"],
     "iparam": ["installation page", "installation parameters","iparam","iparams","iparam.json","iparam_test_data","custom_configs","client.iparams","template substitution","<%=","getconfigs","postconfigs","iparams.html","custom installation","install page", "custom iparams","installation screen"],
     "request-method": ["request api","client.request","$request","static ip","request method","get request","post request"],
     "frontend-framework": ["frontend framework","vue js","react","angular","ember","svelte","babel"],
     "placeholder":["full_page_app","sidebar","cti_global_sidebar","ticket_sidebar","ticket_requester_info","ticket_top_navigation","ticket_attachment","ticket_conversation_editor","time_entry_background","contact_sidebar","contact_background","contact_list_background","company_background","company_list_background","new_ticket_requester_info","new_ticket_background","new_email_requester_info","new_email_background","change_sidebar","change_background","asset_sidebar","conversation_user_info","conversation_message_editor","conversation_background","contact_entity_menu","deal_entity_menu","sales_account_entity_menu","left_nav_cti","job_boards","notification_card","conversation_card","widget_notification_card","widget_conversation_card"],
     "cti":["cti","cti app"],
     "custom-objects":["custom entities","custom objects","co","entities.json"],
     "custom-field":["custom fields","cf_"],
     "oauth":["oauth","oauth_config","isoauth","access_token","client_id","client_secret","authorize_url","token_url","oauth_iparams","authorization grant","refresh token","auth/callback"],
     "interface-method":["interface api","client.interface","show modal","instance context","show dialog","show confirm","confirmation dialog box","showNotify","show notification","show cti","hide cti","interface trigger","show field","hide field","enable field","disable field","editor window"],
     "serverless":["serverless","server.js","npm","devdependencies","require"],
     "product-events": ["product event","app setup event","onTicketCreate","onTicketUpdate","onConversationCreate","onContactCreate","onContactUpdate","onCompanyCreate","onCompanyUpdate","onCompanyDelete","onTimeEntryCreate","onTimeEntryUpdate","onTimeEntryDelete","onDealCreate","onDealUpdate","onSalesAccount","onCustomModule","onAppointment","onTaskCreate","onTaskUpdate","onCallCreate","onCallUpdate","onEmployeeCreate","onEmployeeUpdate","onNewHireCapture","onNewHireUpdate","onJobPostingCreate","onJobPostingUpdate","onTimeOffCreate","onTimeOffUpdate","onMessageCreate","onUserCreate","onUserUpdate","web/test"],
     "frontend-events":["client.events","click event","change event","intercept event","event.helper.getdata"],
     "webhook":["webhook","external events","hooks.freshworks.com","onExternalEvent","web hook","generateTargetUrl"],
     "data-storage":["client.db","$db","localstore","data storage"],
     "data-method":["data method","loggedinuser","domain name","email_config","time sheet object","_options","client.data","time_entry","requester details"],
     "scheduled-events":["scheduled events","one time schedule","recurring schedule","$schedule"],
     "instance-method":["client.instance","resize app","parent to modal","modal to parent","instance context","instance receive","instance send"],
     "rest-api":["rest api","product api","freshdesk api","freshservice api","freshchat api","freshteam api","freshcaller api","freshworks api","apis","api/v2"],
     "api-key":["api key","api token","product key","account credentials","account key"],
     "test-framework":["serverless testing","test framework","serverless tests","mocha"],
     # product
     "freshdesk":["freshdesk","desk"],
     "freshservice":["freshservice","service"],
     "freshchat":["freshchat","chat"],
     "freshcaller":["freshcaller","caller"],
     "freshworks_crm":["crm","freshworks crm"],
     "freshsales":["freshsales"],
    #  App Related
     "app-structure": ["manifest","platform version","domain whitelisting"],
     "custom-app":["custom app","private app"],
     "external-app":["external app"],
     "paid-app":["paid app"],
     "public-app":["public app","free app","marketplace app"],
     "omni-app":["multi product app","omni app"],
     # Platform
     "middleware":["middleware"],
     "rate-limit":["rate limit","throttle","429","too many request"],
     "app-mgmt-portal":["developer portal","dev portal","app portal","app management portal","AMP","app submission","app listing","deploy"],
     "app-installation":["renderData","onAppInstall","onAppUninstall","app installation","app gallery","uninstall","uninstallation"],
     "documentation":["docs","documentation","sdk docs","api docs"],
     "security":["authentication","security","authorization","confidential","sensitive"],
     "integration":["third party api","3rd party","integration","third party"]
 }
